---
title: Extrapolating by Inverse Optimization
author:
date: '2019-03-09'
slug: extrapolating-by-inverse-optimization
categories: []
tags:
  - Optimization
  - Linear programming
---
*Wherein I present a simple example of a prediction problem modeled as inverse optimization, with a brief detour into Bayesian estimation, peppered with snide remarks about data science as it is commonly practiced.* 


Let us imagine a grocer (let's call her Alice) trying to esimate the impacts of changing the pricing of her produce on the purchase behavior of her customers. Following the advice of her data scientist friend she gathers her database of quantities of produce purchased by individual customers under various pricing regimes, and hands him the trove. 

The collected data looks something like the following. (In each row the prices and quantities are for _all_ the products Alice sells.)

```{r echo=F, results="asis"}
library(knitr)
df = data.frame(Date = c("Jan 1", "Jan 8", "Feb 4", "..."), Customer.ID = c("XYZ", "ABC", "XYZ", "..."), Price.Vector = c("[$3.2, $2.5, $1.0, ...]", "[$2.0, $2.0, $1.5, ...]", "[$2.5, $2.0, $1.8, ...]", "..."), Quantity.Vector=c("[1 lb, 0.0 lb, 0.0 lb, ...]", "[0.0 lb, 0.0 lb, 0.5 lb, ...]",  "[1.0 lb, 0.0 lb, 0.1 lb, ...]", "..."))
kable(df)
```

The data scientist friend doesn't see what the big problem is. He builds deep learning models in his sleep and this seems like a simple regression problem. He could just build a machine to predict the quantities column from the price column and take the afternoon off. 

Alas it was not to be; the price vectors that Alice wants to plug into the trained regression model are well outside the ranges of the ones she provided the data scientist for training. She does not see the point of any such modeling if it doesn't enable extrapolation. She is appalled by the resulting nonsensical predictions, that her friend assures her were produced by algorithms indistinguishable from the ones that in the near future will drive her around town.

A Physics of Purchase Behavior
------------------------------
Alice decides to take a less shallow approach and write out what she knows about the problem and how it relates to what she wishes to estimate. 

She reasons that each of her customers $\smash{c_i}$ has a weekly budget $\smash{b_{i}}$ for produce ($\smash{t}$ stands for the date of the store visit) and a personal produce value vector $\smash{v_i}$. (She makes the simplifying asssumption that the budget does not vary from week to week.) Each customer may have their individual constraints on the purchases 

She hypothesizes that a customer on every weekly visit looks at the produce price vector $\smash{p_t}$, and mentally runs a simple optimization of the following form to decide what quantities of each item of produce ($\tilde{x}_{it}$) he will purchase:  

$$\begin{aligned}
\tilde{x}_{it} &= \mbox{maximize}_x f(x, v_i) \\
\mbox{subject to} &\;\; \smash{p_t'} x \leq b_{i}
\end{aligned}
$$


